export const SIGN_IN = "SIGN_IN";

export const SIGN_OUT = "SIGN_OUT";

export const USER_CREATED_SUCCESS = "USER_CREATED_SUCCESS";

export const FORGOT_PASSWORD_CLICKED = "FORGOT_PASSWORD_CLICKED";

export const SPINNER_OVERLAY = "SPINNER_OVERLAY";

export const USER_DATA = "USER_DATA";

export const FRIEND_REQUESTS = "FRIEND_REQUESTS";

export const ONLINE_STATUS = "ONLINE_STATUS";

export const NOTIFICATIONS = "NOTIFICATIONS";

export const CHAT_REQUESTS = "CHAT_REQUESTS";

export const CHAT_MESSAGES = "CHAT_MESSAGES";

export const CHAT_STATUS = "CHAT_STATUS";

export const CLEAR_SESSION = "CLEAR_SESSION";

export const WS_LIST = "WS_LIST";

export const LAST_SEEN = "LAST_SEEN";

export const HAS_READ = "HAS_READ";

export const MSG_COUNT = "MSG_COUNT";

export const IS_TYPING = "IS_TYPING";

export const CHAT_DELETE = "CHAT_DELETE";

export const LAST_CHAT_SEEN_TIME = "LAST_CHAT_SEEN_TIME";

export const CURRENT_CHAT = "CURRENT_CHAT";

export const CONVERSATION_MODAL_DATA = "CONVERSATION_MODAL_DATA";

export const IS_REFRESHED = "IS_REFRESHED";

export const CURRENT_SELECTED_CONVERSATION = "CURRENT_SELECTED_CONVERSATION";

export const CONVERSATION_DELETE = "CONVERSATION_DELETE";

export const MANAGE_REQUESTS_COUNT = "MANAGE_REQUESTS_COUNT";